// All game dialog lines — edit these to change what people say!

export const introLines = [
  "Time to get to work!",
  "Go get 'em!",
  "You're my best drone!",
  "Make me proud!",
  "Bring everyone\npeace and love!",
  "Have fun out there!",
  "Don't scratch\nthe paint!",
  "Remember your\ntraining!",
  "You were born\nfor this!",
  "I believe in you!",
  "Fly high, friend!",
  "Stay safe up there!",
  "Show 'em what\nyou've got!",
  "You're cleared\nfor takeoff!",
  "The sky is yours!",
  "Spread those wings!",
  "I packed your\nfavorite missiles!",
  "Knock 'em dead!\n...with love!",
  "You're the best\nthing on this\nrunway!",
  "Smooch! Okay\nnow go!",
  "Watch out for\nbirds!",
  "No pressure!\n...okay some\npressure!",
  "Lunch is at noon!\nDon't be late!",
  "Tell the clouds\nI said hi!",
  "Time to hand out\nsome freedom!",
];

export const greetings = [
  "Hi there!",
  "Oh a drone!",
  "Drones are neat!",
  "Hello!",
  "So cool!",
  "Wow look!",
  "Hey friend!",
  "Down here!",
  "Heyyy!",
  "Nice drone!",
  "Is that a Predator?",
  "Come closer!",
  "Do a flip!",
  "Wave back!",
  "I love drones!",
  "Fly safe!",
  "You're amazing!",
  "Take my photo!",
  "Over here!",
  "Wooooo!",
  "Go go go!",
  "So majestic!",
  "Beautiful!",
  "I want one!",
  "How high\nare you?",
  "Incredible!",
  "Zoom zoom!",
  "Big bird!",
  "Living the\ndream!",
  "Can I get\na ride?",
  "Show off!",
  "Tell the CIA\nI said hi!",
  "Top Gun\nvibes!",
  "Brrrrt!",
  "You seeing\nthis?!",
  "Look mom!",
  "The future\nis now!",
  "USA! USA!",
  "Oh look!",
];

export const ghostLines = [
  "Thanks!",
  "I hated this\nplace anyway",
  "Finally!",
  "Sweet release!",
  "About time!",
  "Freedom!",
  "Weeee!",
  "Best day ever!",
  "No more taxes!",
  "Tell my wife\nI said bye!",
  "5 stars!",
  "Do it again!",
  "That was fun!",
  "I needed that!",
  "Cozy!",
  "Worth it!",
  "Bye bye legs!",
  "I feel so light!",
  "Rent free now!",
  "GG!",
  "This rules!",
  "My back doesn't\nhurt anymore!",
  "Totally worth\nthe wait!",
  "I was so bored!",
  "Incredible!",
  "Much appreciated!",
  "That tickled!",
  "10/10!",
  "Yasss!",
  "I love you\ndrone!",
  "Zero regrets!",
  "Better than\ncoffee!",
  "I can fly now!",
  "See you\nin heaven!",
  "Cloud nine\nliterally!",
  "I'm free!",
  "Delete my\nbrowser history!",
  "Nice shot tho!",
  "...Was that it?",
  "I'm outta here!",
  "Free at last!",
  "Who's going to feed the goat?",
  "Shoot\nI left the stove on",
  "No more work!",
  "Sure, why not.",
  "Finally, a vacation.",
  "Mission accomplished.",
  "That was fun.",
  "Somebody\nfeed my cat!",
  "Grandma??",
  "Ah so relaxing!",
  "I was asking for it.",
  "I deserved that.",
];

export const buildingGhostLines = [
  "Thanks!",
  "I hated this\nplace anyway",
  "Finally!",
  "Sweet release!",
  "About time!",
  "Freedom!",
  "Weeee!",
  "Best day ever!",
  "No more taxes!",
  "The rent was\ntoo high anyway!",
  "Worst hiding\nspot ever!",
  "Should've picked\na different house!",
  "Not again!",
];

export const cheerPhrases = [
  "GOOOL!",
  "Come on!",
  "Yalla!",
  "Offside!",
  "Pass it!",
  "Shoot!",
  "Defense!",
  "Nice one!",
  "Ref!!",
  "Ole!",
];

export const merchantGreetings = [
  "Welcome!",
  "Best prices!",
  "Fresh today!",
  "Come see!",
  "Special deal!",
  "For you,\ndiscount!",
  "Finest quality!",
  "Look! Look!",
];

export const shopperGreetings = [
  "Great finds!",
  "So crowded!",
  "Love this\nmarket!",
  "Need more\nbags!",
  "What a deal!",
  "Smells amazing!",
  "My favorite\nstall!",
  "Haggling is\nan art!",
];

export const shepherdGreetings = [
  "My goats!",
  "Easy now...",
  "Don't scare\nthem!",
  "Shoo! Shoo!",
  "They're friendly!",
  "Want some\ngoat milk?",
];

export const workerGreetings = [
  "Watch your\nhead!",
  "Hard hat\narea!",
  "Oil's flowing!",
  "Careful here!",
  "Don't smoke\nnear the wells!",
  "Shift ends\nat 6!",
  "Black gold!",
  "Pump it up!",
  "Safety first!",
];
